Controllers/OpenTheHatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ThesisApplication.Controllers
{
    public class OpenTheHatchController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FileUpload()
        {
            //return Redirect("~/Views/fileUploads/Create.cshtml");
            return RedirectToAction("Index","fileUploads");
            //return View("~/Views/fileUploads/Create.cshtml");
        }
    }
}

Controllers/userCaseParamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThesisApplication.Data;
using ThesisApplication.Models;

namespace ThesisApplication.Controllers
{
    public class userCaseParamsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public userCaseParamsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: userCaseParams
        public async Task<IActionResult> Index()
        {
            return View("Index");
            //return View(await _context.userCaseParam.ToListAsync());
        }

        // GET: test site
        public IActionResult testSite()
        {
            return View("Index2");
        }

        // GET: userCaseParams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userCaseParam = await _context.userCaseParam.SingleOrDefaultAsync(m => m.ID == id);
            if (userCaseParam == null)
            {
                return NotFound();
            }

            return View(userCaseParam);
        }

        // GET: userCaseParams/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: userCaseParams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Genre,Price,caseDirectory,caseName,metricConversion,modelName,uploadDate,userName")] userCaseParam userCaseParam)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userCaseParam);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(userCaseParam);
        }

        // GET: userCaseParams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userCaseParam = await _context.userCaseParam.SingleOrDefaultAsync(m => m.ID == id);
            if (userCaseParam == null)
            {
                return NotFound();
            }
            return View(userCaseParam);
        }

        // POST: userCaseParams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Genre,Price,caseDirectory,caseName,metricConversion,modelName,uploadDate,userName")] userCaseParam userCaseParam)
        {
            var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToArray();

            if (id != userCaseParam.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userCaseParam);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!userCaseParamExists(userCaseParam.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(userCaseParam);
        }

        // GET: userCaseParams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userCaseParam = await _context.userCaseParam.SingleOrDefaultAsync(m => m.ID == id);
            if (userCaseParam == null)
            {
                return NotFound();
            }

            return View(userCaseParam);
        }

        // POST: userCaseParams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userCaseParam = await _context.userCaseParam.SingleOrDefaultAsync(m => m.ID == id);
            _context.userCaseParam.Remove(userCaseParam);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool userCaseParamExists(int id)
        {
            return _context.userCaseParam.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Digital Wind Tunnel</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <!-- My styles -->
    <link href="~/css/customLayoutStyle.css" rel="stylesheet" />

    <!-- My scripts -->
    <script src="~/js/three.min.js"></script>
    <script src="~/js/three.js"></script>
    <script src="~/js/STLLoader.js"></script>

    <!-- end of my imports -->

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/cranfield_logo_white.png" height="150" width="150" class="logo" /></a>
        <div class="container container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a asp-controller="Home" asp-action="Index" class="navbar-brand">ThesisApplication</a>-->
                <!--<a asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/cranfield_logo_white.png" height="164" width="164" class="logo"/></a>-->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="FileUpload">OPEN THE HATCH</a></li>
                    <li><a asp-controller="Home" asp-action="MeshingStage">MESHING WORKBENCH</a></li>
                    <li><a asp-controller="Home" asp-action="SimulationStage">SIMULATION WORKBENCH</a></li>
                    <!--<li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="userCaseParams" asp-action="testSite">About</a></li>-->
                    
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        <!-- Where all the containers are rendered! -->
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - ThesisApplication</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)

</body>
</html>

Views/Shared/_MeshingWorkbench.cshtml

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--
    WHY LIKE THAT?          TODO
    Inlcuding Jquery to be defined throught entire OpenTheHatch layout!
-->
<link rel="stylesheet" href="~/css/customLayoutStyle.css" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/three.min.js"></script>
<script src="~/js/three.js"></script>
<script src="~/js/STLLoader.js"></script>



    <h3> </h3>
 
            <ul class="nav nav-tabs nav-justified">
                <li><a asp-controller="userCases" asp-action="Index">Case repository</a></li>
                <li><a asp-controller="userCases" asp-action="MeshingIndex">Mesh repository</a></li>
                <li><a asp-controller="userCases" asp-action="viewMesh">Check existing mesh</a></li>
            </ul>

<br /><br /><br />

        @RenderBody()

        @RenderSection("scripts", required: false)



Views/Shared/_OpenTheHatch.cshtml
@model IEnumerable<ThesisApplication.Models.userCase>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/three.min.js"></script>
<script src="~/js/three.js"></script>
<script src="~/js/STLLoader.js"></script>

 <h3> </h3>
<ul class="nav nav-tabs nav-justified">
    <li><a asp-controller="userCases" asp-action="Index">Model repository</a></li>
    <li><a asp-controller="userCases" asp-action="viewFileUpload">View existing model</a></li>
</ul>
<br /><br /><br />

@RenderBody()
     
@RenderSection("scripts", required: false)  


Views/Shared/_SimulationWorkbench.cshtml

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--
    WHY LIKE THAT?          TODO
    Inlcuding Jquery to be defined throught entire OpenTheHatch layout!
-->
<link rel="stylesheet" href="~/css/customLayoutStyle.css" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/three.min.js"></script>
<script src="~/js/three.js"></script>
<script src="~/js/STLLoader.js"></script>


<div class="container">
    <div class="row">
        <div class="navbar">
                <ul class="nav navbar-nav" id="openTheHatch_navbar">
                    <li><a asp-controller="userCases" asp-action="MeshingIndex">Mesh repository</a></li>
                    <li><a asp-controller="userCases" asp-action="viewResults">Check results</a></li>
                </ul>
            </div>
        <div class="row">
                @RenderBody()
        </div>
    </div>
@RenderSection("scripts", required: false)  
</div>

Views/Shared/_partialGeneralHiddenFields.cshtml
@model ThesisApplication.Models.userCase

  <!-- General parameters hidden -->
<input type="hidden" asp-for="ID" />
<input type="hidden" asp-for="caseName" />
<input type="hidden" asp-for="inputFilename" />
<input type="hidden" asp-for="meshStatus" />
<input type="hidden" asp-for="meshedDate" />
<input type="hidden" asp-for="status" />
<input type="hidden" asp-for="unitModel" />
<input type="hidden" asp-for="userName" />
<input type="hidden" asp-for="uploadDate" />


Views/Shared/_partialMeshingHiddenFields.cshtml
@model ThesisApplication.Models.userCase

<!-- Mesh parameters hidden -->
<input type="hidden" asp-for="mesh_refSurfLvlMax" />
<input type="hidden" asp-for="mesh_refSurfLvlMin" />
<input type="hidden" asp-for="mesh_numLayers" />
<input type="hidden" asp-for="mesh_expRatio" />
<input type="hidden" asp-for="mesh_finLayerThickness" />
<input type="hidden" asp-for="mesh_minThickness" />

<input type="hidden" asp-for="mesh_refRegDist1" />
<input type="hidden" asp-for="mesh_refRegLvl1" />
<input type="hidden" asp-for="mesh_refRegDist2" />
<input type="hidden" asp-for="mesh_refRegLvl2" />
<input type="hidden" asp-for="mesh_refRegDist3" />
<input type="hidden" asp-for="mesh_refRegLvl3" />

Views/Shared/_partialSimulationHiddenFields.cshtml
@model ThesisApplication.Models.userCase




<!-- Simualation hidden field -->
<input type="hidden" asp-for="visualization_operatingPressure" />
<input type="hidden" asp-for="visualization_operatingtemperature" />

<input type="hidden" asp-for="visualization_flowDirectionX" />
<input type="hidden" asp-for="visualization_flowDirectionY" />
<input type="hidden" asp-for="visualization_flowDirectionZ" />
<input type="hidden" asp-for="visualization_flowSpeed" />

<input type="hidden" asp-for="visualization_numProbes" />
<input type="hidden" asp-for="visualization_numCuts" />

<input type="hidden" asp-for="visualization_probe1x" />
<input type="hidden" asp-for="visualization_probe1y" />
<input type="hidden" asp-for="visualization_probe1z" />

<input type="hidden" asp-for="visualization_probe2x" />
<input type="hidden" asp-for="visualization_probe2y" />
<input type="hidden" asp-for="visualization_probe2z" />

<input type="hidden" asp-for="visualization_probe3x" />
<input type="hidden" asp-for="visualization_probe3y" />
<input type="hidden" asp-for="visualization_probe3z" />

<input type="hidden" asp-for="visualization_normal1x" />
<input type="hidden" asp-for="visualization_normal1y" />
<input type="hidden" asp-for="visualization_normal1z" />
<input type="hidden" asp-for="visualization_point1x" />
<input type="hidden" asp-for="visualization_point1y" />
<input type="hidden" asp-for="visualization_point1z" />

<input type="hidden" asp-for="visualization_normal2x" />
<input type="hidden" asp-for="visualization_normal2y" />
<input type="hidden" asp-for="visualization_normal2z" />
<input type="hidden" asp-for="visualization_point2x" />
<input type="hidden" asp-for="visualization_point2y" />
<input type="hidden" asp-for="visualization_point2z" />

<input type="hidden" asp-for="visualization_normal3x" />
<input type="hidden" asp-for="visualization_normal3y" />
<input type="hidden" asp-for="visualization_normal3z" />
<input type="hidden" asp-for="visualization_point3x" />
<input type="hidden" asp-for="visualization_point3y" />
<input type="hidden" asp-for="visualization_point3z" />